### ISSUE TITLE
'client' was not declared in this scope

### ISSUE THREAD

**Issue by maba64** [3KUdelta/Solar_WiFi_Weather_Station#14]
Hi there
Thank you for your code

I get an error message while compiling

exit status 1
'client' was not declared in this scope

 while (client.connected() || (WiFi.status() == WL_CONNECTED)) {

Thank you for your support

Maba

**Comment by 3KUdelta** [comment]
Should be working now with Tomasz' corrections.

**Comment by maba64** [comment]
Thank you??
________________________________
