### ISSUE TITLE
Error compiling of the 2.3 version on Wemos d1 Pro

### ISSUE THREAD

**Issue by keesvw** [3KUdelta/Solar_WiFi_Weather_Station#2]
Hi First of all much respect for your moderation and improvement of the 2.3 version and I would like to get it working also.. The 2.0 model works fine and and get it all working and was also my first IoT project and made me curious to expand it further.
Also I get stuck when compiling your code.

1. I managed to add the adafruits and the blynk libraries but it keeps stalling on not being able to find the espwifi.h library (see screenshot). Perhaps I make a beginner mistake and would appreciate a small push to get me further.
![espwifi](https://user-images.githubusercontent.com/36747428/58917490-122e2880-8727-11e9-9933-95454141629d.png)

2. I also added the GY-1145 and add a DS18B20 to monitor a 2nd temperature. I want to make a case modding by adding a window with some perspex so the UV sensor could house there and provide via Blynk a UV warning. I was wondering if you could modify the code  as such that it can read those 2 sensors.

Much appreciate if you could assist me 

Kees

**Comment by djbriane** [comment]
I'm also running into the same issue - tried searching for that header file but haven't had any luck. I presume it is part of the ESP8266 library but looking through it's source I can't find it.

**Comment by djbriane** [comment]
Solved this by changing `ESPWiFi.h` to `ESP8266WiFi.h` and everything seem to be working fine now.

**Comment by keesvw** [comment]
Got that part working now as well; But now it stalls at:
exit status 1
Errot in compil bij het compileren voor board LOLIN(WEMOS) D1 mini Pro

Van: Brian Erickson <notifications@github.com>
Verzonden: dinsdag 11 juni 2019 05:29
Aan: 3KUdelta/Solar_WiFi_Weather_Station <Solar_WiFi_Weather_Station@noreply.github.com>
CC: keesvw <kees_work@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [3KUdelta/Solar_WiFi_Weather_Station] Error compiling of the 2.3 version on Wemos d1 Pro (#2)


Solved this by changing ESPWiFi.h to ESP8266WiFi.h and everything seem to be working fine now.

**Comment by djbriane** [comment]
I'm not sure about that error, is there anything else in the output? 

Without seeing more all I can suggest is make sure you have all the libraries installed for your board (although I'd assume those would show up in the error log if missing). The other thing I had to do was install the USB drivers for the Wemos D1 (on my Mac) - make sure you've done that as well (though this looks like a compile error rather than a programming issue).
