### ISSUE TITLE
Could not connect to NTP Server! fail

### ISSUE THREAD

**Issue by MrO-art** [3KUdelta/Solar_WiFi_Weather_Station#24]
Dear all,

the code stops here:
20:10:45.364 -> ---> Now reading time from NTP Server
20:10:47.751 -> ....................Could not connect to NTP Server!
20:11:34.798 -> Doing a reset now and retry a connection from scratch.

changed the server - nothing happend-

Any Idea?
thx
Michael

**Comment by 3KUdelta** [comment]
Hi Michael

just to be sure. Did you load the right library from Github and copied the folder into Arduino/libraries?
`#include <EasyNTPClient.h>       //https://github.com/aharshac/EasyNTPClient`
The server should not be the problem.
