### ISSUE TITLE
Is there a variation of the Code where BMP280 is used instead of the BME280?

### ISSUE THREAD

**Issue by OsBenji** [3KUdelta/Solar_WiFi_Weather_Station#33]
Hi,
In order to spare some Money (and I don't need Air Pressure) I decided to use the cheaper BMP280 Sensors instead of the BME280. unfortunately, the Code only covers the BME280 Sensor. So how can someone who just started change the Code so it will work with the BMP280 Sensors?

**Comment by 3KUdelta** [comment]
Hello, the pressure sensor is needed to do the forecasting. For the super simple software layout you can go back to the original built by Debasish. --> https://www.instructables.com/id/Solar-Powered-WiFi-Weather-Station-V20/
I think you save 1 Dollar doing this.
