### ISSUE TITLE
Typo in Translation.h. for norwegian language

### ISSUE THREAD

**Issue by f45tb00t** [3KUdelta/Solar_WiFi_Weather_Station#34]
Hello 3KUdelta,

thanks a lot for your code. This is awesome. With your last commit you uploaded a not working translation.h file.

It is "#if LANGUAGE == 'NO'" but should be "#elif LANGUAGE == 'NO'

KR
fastboot

**Comment by drkoraytuncer** [comment]
Yes, exactly.
If it doesn't corrected the sketch stop with error code.

**Comment by 3KUdelta** [comment]
Thank you, I was too quick to accept the pull request ;-)
- corrected.
