### ISSUE TITLE
Missbehavior in creating wifi connection

### ISSUE THREAD

**Issue by f45tb00t** [3KUdelta/Solar_WiFi_Weather_Station#35]
Hello,

I am not sure if this was implemented intentionally or by mistake.
But your code opens unwanted Open and unencrypted APs after wake up.
I consider this as a potential security issue.

If it was made by design. Why?

To fix this issue you can add the following (or change partially the code)

Example:
WiFi.mode(WIFI_STA);
WiFi.hostname(DEVICENAME);
WiFi.begin(ssid, pass);

The WiFi.mode(WIFI_STA); must be added before the WiFi.begin(ssid, pass);

Kind Regards

fastboot

**Comment by f45tb00t** [comment]
Hello,

I am not sure if this was implemented intentionally or by mistake. 
But your code opens unwanted Open and unencrypted APs after wake up.
I consider this as a potential security issue. 

If it was made by design. Why?

To fix this issue you can add the following (or change partially the code)

Example:
  WiFi.mode(WIFI_STA);
  WiFi.hostname(DEVICENAME); 
  WiFi.begin(ssid, pass);

The WiFi.mode(WIFI_STA); must be added before the WiFi.begin(ssid, pass);

Kind Regards

fastboot

**Comment by 3KUdelta** [comment]
Hi fastboot, thank you for this hint. Definitely a mistake. 
I will change accordingly. 
Marc
