### ISSUE TITLE
upgrade 

### ISSUE THREAD

**Issue by danielec1980** [3KUdelta/Solar_WiFi_Weather_Station#41]
congratulations for the code, it's a good job!
I made the metereligca station almost a year ago!
it would be nice to implement with some sensors (for example for wind and rain) and maybe a webcam.

Are you planning to develop any upgrades?
thanks

Daniele

**Comment by 3KUdelta** [comment]
Hello Daniele
It is not so difficult to add more sensors. You can find some forks here top right on the page. Maybe you want look at Frank Ulbricht´s  solution, he has added more sensors. Please consider that the weather station is built for minimal power consumption. A wind-sensor or a webcam for example will need constant power so it would need a different architecture.
Sorry, but I won't develop some upgrades. I'd rather suggest to you to start a new project.
Marc
