### ISSUE TITLE
Cannot verify

### ISSUE THREAD

**Issue by ESF-nl** [3KUdelta/Solar_WiFi_Weather_Station#42]
After downloading the Solar Wifi Weather Station I cannot verify the program. This error appears in Arduino IDE:

`invalid conversion from 'char*' to 'const uint8_t* {aka const unsigned char*}' [-fpermissive]`

while this row is marked:
`client.publish("home/weather/solarweatherstation/zletter", tmp1, 1);         // ,1 = retained`

Who can help me please?

**Comment by 3KUdelta** [comment]
Delete these lines and you´ll be fine.
```
char* tmp1 = &z_letter;
client.publish("home/weather/solarweatherstation/zletter", tmp1, 1);         // ,1 = retained
delay(50);
```
You probably do not need the Z-Letter in MQTT. I did some tests and never deleted it again.
Btw. if you don´t need MQTT, please use Solar-WiFi-Weather-Station-V2.3.ino instead.

**Comment by ESF-nl** [comment]
Thank you for you swift reply! I was really interested in the MQTT version as I'm trying to connect the weather data to my Domoticz :-)

I've deleted these line but than the same error appears here:
`  client.publish("home/weather/solarweatherstation/trend", _trend, 1);      // ,1 = retained`
and if I delete that one as well, the 3rd same error is here: 
`  client.publish("home/weather/solarweatherstation/trendinwords", tmp2, 1);`

Should all that rows also be deleted?

I found also this topic about this error but I do not know how to implement it in your code.
(https://forum.arduino.cc/index.php?topic=586641.0)

**Comment by 3KUdelta** [comment]
Well, then it is another problem. You should not have to delete all the client.publish lines just because the conversion error. 
Please double check: - right board settings under "Tools"?

**Comment by ESF-nl** [comment]
Yes, I have "LOLIN(WEMOS) D1 mini Pro" selected

**Comment by 3KUdelta** [comment]
Strange - I just compiled the code with no errors. 
My environment: Arduino 1.8.13 (Mac)

**Comment by 3KUdelta** [comment]
Please reload code from Github again, recompile and copy the full error log.

**Comment by ESF-nl** [comment]
Thank you again for your patience helping a beginner.

I used the preferences to also create an expanded log.
[Error log.txt](https://github.com/3KUdelta/Solar_WiFi_Weather_Station/files/6176399/Error.log.txt)
[Error log expanded.txt](https://github.com/3KUdelta/Solar_WiFi_Weather_Station/files/6176400/Error.log.expanded.txt)

**Comment by 3KUdelta** [comment]
I found this: Bibliotheek pubsubclient-master op versie 1.99.1
Try to update to V 2.8 (actual) --> [https://github.com/knolleary/pubsubclient](https://github.com/knolleary/pubsubclient)

**Comment by ESF-nl** [comment]
Yes the program has been uploaded into my Wemos! Great you found the issue. 
Now I'm going to add sensors :-)
