### ISSUE TITLE
Infinite deepSleep

### ISSUE THREAD

**Issue by jgiunta** [3KUdelta/Solar_WiFi_Weather_Station#46]
Hello, how are you ?

First congrat for your amazing work.

I have a question about th euse of deepSleep(0) when de battery is below 3.3v.  What's happen if we have 3.3v on night and on day the battery don't power off (due to lack of energy) and charge to 4v. With this scenario I would never transmit information again since I would be hibernating forever.

The documentation about deepSleep(0) said:

"To put the ESP8266 in deep sleep mode for an indefinite period of time use ESP.deepSleep(0). The ESP8266 will wake up when the RST pin receives a LOW signal."

I don't know if I'm wrong with my explanation, but I think it will works that way.

Thanks!

**Comment by 3KUdelta** [comment]
Hi, you are right - deep sleep will only wake up if recharged and button pressed. This is my idea of saving the battery from overdischarging. You can also change the deepSleep(x) in setting your own time (x).
