### ISSUE TITLE
ThingSpeak not updating anymore

### ISSUE THREAD

**Issue by polanskiman** [3KUdelta/Solar_WiFi_Weather_Station#48]
Hello,

Due to some update done on ThingSpeak's end, the code is broken and data is not being sent anymore to ThingSpeak servers. It is discussed here: https://www.mathworks.com/matlabcentral/discussions/thingspeak/745015-all-my-thingspeak-channels-stopped-receiving-data-on-the-same-date-april-13th-2022-at-around-10-00?s_tid=srchtitle

Since I don't often check my ThingSpeak channel, I actually only noticed a few days ago that my ThingSpeak Channel also stopped receiving data at the exact same date (April 13). Having little to no knowledge on coding I can't fix this myself.

Any help would be appreciated.

Thank you.

**Comment by Maigoland** [comment]
Hi
I have the same problem, the last data published in ThingSpeak is on 2022/12/4.

Any ideas to solve this problem?

Thanks

**Comment by 3KUdelta** [comment]
It seems that they have changed parts of the file format. I did not notice it either. Probably not a big deal - I will have a look into it.

**Comment by polanskiman** [comment]
Seems to be an url encoding issue. Spaces should be formated as %20
Here it is disscussed too: https://www.mathworks.com/matlabcentral/discussions/thingspeak/744635-channel-status-update-strings-including-space-chars?s_tid=srchtitle

**Comment by 3KUdelta** [comment]
Do you want to try to fix it? I can start looking into it coming Sunday.

**Comment by polanskiman** [comment]
I would if I had the knowledge. It can wait. It’s been down for 5 months, a few more days won’t change anything ;)

**Comment by polanskiman** [comment]
If I may suggest, in addition to the fix above, it might be worth adding some piece of code to know what happened when a requests was sent to the server. As it currently is, there is no feedback and nothing is printed in the serial monitor as to wether the request was successful or not. We get a "Data written to Thingspeak ..." but that happens no matter what, so it's not very useful to track connection problems.

**Comment by 3KUdelta** [comment]
Good idea - will look into it.

**Comment by polanskiman** [comment]
Wanting to find the solution I contacted ThingSpeak directly. So far I haven't found the way, however at ThingSpeak they recommended using the ThingSpeak library for arduino and esp instead.

https://www.mathworks.com/matlabcentral/answers/1789110-thingspeak-channel-stopped-receiving-data-since-april-13th-2022

**Comment by 3KUdelta** [comment]
Fixed it with by using the ThingSpeak library. Please be aware that you need to enter your channel id and your key in Settings.h.

**Comment by polanskiman** [comment]
Awesome. Will try it out.

**Comment by polanskiman** [comment]
All is working smoothly for me now. Also thank you for pointing out the Blynk code will be deprecated by the end of the year. I will try to look into how to update it. Gives me 4 months to learn about coding ;)

**Comment by jspanitz** [comment]
> Blynk code will be deprecated by the end of the year

Hmm, where is this noted and what does it mean in terms of using the existing blynk app - will it stop working or just be unsupported?

Edit: Found on main project page:
https://blynk.io/blog/what-will-happen-to-the-legacy-blynk-platform

So basically, this project is dead for anyone just starting out - lovely!

**Comment by 3KUdelta** [comment]
Not quite true - there are so many replacements:
- ThingSpeak Clients for Android and iPhone (working)
- MQTT (working)
- Arduino IoT Remote (needs to be integrated)
- New Blynk (has also some free version - needs to be integrated)

**Comment by polanskiman** [comment]
@jspanitz I have updated the code in my fork to work with the New Blynk. Have a look at it. Changes are really minimal.

**Comment by 3KUdelta** [comment]
I finally found some time  - thank you @polanskiman for your input. I also have done the few updates for Blynk. It is more to do on Blynk's side than on the code here.
