### ISSUE TITLE
The settings file needs to be updated

### ISSUE THREAD

**Issue by zangaby** [3KUdelta/Solar_WiFi_Weather_Station#51]
Hello,

The latest version of the blynk library is now expecting to define
#define BLYNK_TEMPLATE_NAME "Solar Weather Station"
instead of
#define BLYNK_DEVICE_NAME "Solar Weather Station"

**Comment by 3KUdelta** [comment]
Thank you for this hint. More to read at [blynk's pages](https://docs.blynk.io/en/getting-started/template-quick-setup/prepare-code)
