### ISSUE TITLE
Compilation error: Settings_mst.h: No such file or directory

### ISSUE THREAD

**Issue by maba64** [3KUdelta/Solar_WiFi_Weather_Station#53]
I get this error
fC:\Users\mabab\Downloads\Solar_WiFi_Weather_Station-master (4)\Solar_WiFi_Weather_Station-master\Solar-WiFi-Weather-Station-V2.4\Solar-WiFi-Weather-Station-V2.4.ino:95:10: fatal error: Settings_mst.h: No such file or directory
   95 | #include "Settings_mst.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: Settings_mst.h: No such file or directory
Markus

**Comment by 3KUdelta** [comment]
Hi Markus,

thank you for mention this - my bad. I corrected the file. It should be #include "Settings.h" on line 95.

Marc

**Comment by maba64** [comment]
hi Mark
but i get a new error....
thanks

________________________________

**Comment by 3KUdelta** [comment]
OK, you opened an new issue - closing this one.
Marc
