### ISSUE TITLE
broker.hivemq.com

### ISSUE THREAD

**Issue by maba64** [3KUdelta/Solar_WiFi_Weather_Station#55]
have a problem with "broker.hivemq.com although I have activated it and created an account no data is sent
I do not receive an error message
any Idea?
thanks
br
Markus

**Comment by 3KUdelta** [comment]
Hi Markus,
how to you know that there is no message sent?
Look at your settings. 

```
bool MQTT = true;                             // If you use MQTT, set to true, else false

const char* mqtt_server = "broker.hivemq.com";       // MQTT Server (broker) address
const char* mqtt_user = "";                          // MQTT Server (broker) userid
const char* mqtt_pass = "";                          // MQTT Server (broker) password
const char* mqtt_topic = "YOUR_TOPIC";  // e.g. myname/weather/my_location
const char* mqtt_status = "YOUR_STATUS"; // e.g. myname/status
```


Whatever you have set as for variable mqtt_topic you should be able to read back from hivemq. So if you have "myname/weather/zurich" you can use any free MQTT explorer (examples in Apple environments: iOS: MQTTAnalyzer, Mac: MQTT Explorer) and there you need to connect to mqtt://broker.hivemq.com Port: 1883 and subscribe to myname/# - then you should see the published messages.

Hope this helps.
Marc

**Comment by maba64** [comment]
Hi Marc
this are the serveradress?
[cid:83c16fe6-af01-478c-af99-688b0fc637dd]


and this the User Name ? "mabazug"
[cid:e6a45f68-a823-49c0-a494-e5e08135a67b]


and "wetter" the topic ?

and the status ?
Br Markus
________________________________
Von: Marc ***@***.***>
Gesendet: Donnerstag, 30. Mai 2024 09:22
An: 3KUdelta/Solar_WiFi_Weather_Station ***@***.***>
Cc: maba64 ***@***.***>; Author ***@***.***>
Betreff: Re: [3KUdelta/Solar_WiFi_Weather_Station] broker.hivemq.com (Issue #55)


Hi Markus,
how to you know that there is no message sent?
Look at your settings.

bool MQTT = true;                             // If you use MQTT, set to true, else false

const char* mqtt_server = "broker.hivemq.com";       // MQTT Server (broker) address
const char* mqtt_user = "";                          // MQTT Server (broker) userid
const char* mqtt_pass = "";                          // MQTT Server (broker) password
const char* mqtt_topic = "YOUR_TOPIC";  // e.g. myname/weather/my_location
const char* mqtt_status = "YOUR_STATUS"; // e.g. myname/status


Whatever you have set as for variable mqtt_topic you should be able to read back from hivemq. So if you have "myname/weather/zurich" you can use any free MQTT explorer (examples in Apple environments: iOS: MQTTAnalyzer, Mac: MQTT Explorer) and there you need to connect to mqtt://broker.hivemq.com Port: 1883 and subscribe to myname/# - then you should see the published messages.

Hope this helps.
Marc

**Comment by 3KUdelta** [comment]
Hi Markus,

Serveraddress: mqtt://broker.hivemq.com Port: 1883, no username, no password
You can use any topic you like. The idea is to use a topic which is unique, so you can subscribe to it at any time.
So, you could use mabazug/wetter as your topic. If you will have more than one station, you´d better take mabazug/wetter/station1. I hope you understand the logic. You are totally free in structuring your topic(s).

Best Marc

**Comment by maba64** [comment]
and whats about this adress ?
![111](https://github.com/3KUdelta/Solar_WiFi_Weather_Station/assets/59450467/0d1701ea-3b32-43b3-ba97-0f9d4c8d012f)

c5b730500cd34edbace6696a96113031.s1.eu.hivemq.cloud

**Comment by 3KUdelta** [comment]
You simply don't need it. Just use the open port for everyone. No account, no plan, no password. If you believe your weather data is secret or you need a private account then go for it. But I am not sure if I can help you with this. 
Marc
