### ISSUE TITLE
Using BMP180

### ISSUE THREAD

**Issue by Bigben83** [3KUdelta/Solar_WiFi_Weather_Station#6]
Have you got a copy of the script that uses the BMP180?

**Comment by 3KUdelta** [comment]
https://github.com/adafruit/Adafruit-BMP085-Library/blob/master/examples/BMP085test/BMP085test.ino
There is this comparable library from Adafruit - just exchange the components.

**Comment by Bigben83** [comment]
Ok great I have modified the .ino to use either now.
